### PR TITLE
Fix comment wording to correspond to option

### PR DESCRIPTION
**Pull request by krlmlr**
Can you please confirm that I'm reading this minimal example correctly, or clarify? The comment "don't remove" seems inconsistent with the "exclude" option.

### CODE REVIEW

**Comment by mikelalcon** [comment]
No, actually documentation is "right" (not really, as it should use `exclude =["third_party/copybara/README_INTERNAL.txt"]` instead of just `README_INTERNAL.txt`).

Imagine you have: `destination_files = glob(["foo/*"])`. If `foo/internal.txt` already exists in the destination, we cannot differentiate between the file being internal only or been deleted on the origin. But if you use `destination_files = glob(["foo/*"], exclude =["foo/internal.txt"])`, now we know that we shouldn't care about that file in the destination, even if not present in the origin.

**Comment by krlmlr** [comment]
Thanks. How do you feel about a simple copycat example (one step prior to that first example) that simply mirrors? I suspect the commands contained there could be considered as some of the "most important commands"?

**Comment by krlmlr** [comment]
Maybe if this example comes with a shell script that sets up everything and shows how the mirroring works? Happy to contribute.

**Comment by mikelalcon** [comment]
I think this is the minimal meaningful example of Copybara. If just moving everything from one repo to another, it is better to use `git.mirror`. `core.workflow` is mean to be used when not all the files are copied or some transformations are made to the code.

We have two examples, one for importing code (the first one) and another one for exporting to GitHub (the most common).

**Pull request closed without merging**
