### PR TITLE
Add a ssh GitHub example based on my experience

### PR DESCRIPTION
**Pull request by DarthHater**
This takes some of the config I generated for a @sonatype project, generalizes it and adds it as an example for others.

Let me know if there is anything you'd like me to adjust, greatly appreciate the help you've all been thus far.

### CODE REVIEW

**Comment by DarthHater** [comment]
I signed it (we signed it)!

**Comment by mikelalcon** [comment]
Sorry for the inconveniences :( . One last thing. The commit author currently is a gmail account but needs to be one from your company. Would you mind amending the commit with that email address?

Thanks,
Mikel.

**Comment by DarthHater** [comment]
Ah I figured it was that. I'll do that.

**Comment by denian** [comment]
Hi Jeffry,

Your change has been imported to our internal repo, and exported to master:
https://github.com/google/copybara/commit/86b388d23d69a707cf7233064befd3f78fb4e3bf

This is the process we have in place in order to keep our internal repo as the source-of-truth.

Thanks for your contribution!

**Pull request closed without merging**
