### PR TITLE
Do not assume github.com in git repository url validation

### PR DESCRIPTION
**Pull request by simontoens**
We'd like to use Copybara with our internally hosted GHE.

### CODE REVIEW

**Comment by mikelalcon** [comment]
Hi Simon,

In order for us to review that change we need your company to sign the CLA.

Cheers,
Mikel.

**Comment by simontoens** [comment]
Hi @mikelalcon - my company, Salesforce.com has signed it.  The email address associated with this commit is "stoens@salesforce.com", and I also added that email address to my GitHub account right now.  
When I click on the "your existing CLA data" link above, it says: "You are covered by the following corporate agreements: "Google Corporate CLA - Salesforce - Jul 01, 2016 12:04 PDT".  
Do you know what else I need to do?

**Comment by mikelalcon** [comment]
Hi again Simon,

Sorry for the late response. The change looks good but, have you tested with change and works for your case? We depend on several places on the hardcoded "github.com" string (If you want to use git.github_pr{origin,destination}.

I think we could change most of them with a flag if needed.

**Comment by mikelalcon** [comment]
merged in de762d1473063082f9e86d165d2cc4ea5864a4be

Thanks for the contribution!

**Comment by simontoens** [comment]
@mikelalcon thanks - we have not run into any other issues related to "github.com" hardcoding yet, will send more PRs if/when we do...

**Pull request closed without merging**
