### PR TITLE
Add hash for Bazel external workspace.

### PR DESCRIPTION
**Pull request by benjaminp**

### CODE REVIEW

**Comment by mikelalcon** [comment]
This doesn't work for us, we have an automatic process that scans Bazel and updates it:

https://github.com/google/copybara/blob/master/third_party/bazel.bzl

**Comment by benjaminp** [comment]
Can said automated process add a hash?

**Comment by mikelalcon** [comment]
Not for now, but probably wouldn't add much security.

That process updates the SHA-1 pointer to the Bazel Git repo. The Sha-256
is is the hash of the zip of the sources. But if we call github and fetch
the zip file to compute the hash, we are basically trusting GH that it
serves us the good file at that point.

**Comment by benjaminp** [comment]
I admit the main reason I want a hash here is that otherwise Bazel prints a noisy message whenever building copybara.

**Comment by mikelalcon** [comment]
:)

Internally this has been requested from time to time for bumping
third_party dependencies in git. But we don't have a good answer :(. The
fetch of the zip file for big repos is a bit brutal, as we are effectively
downloading all the contents again, without the git cache.

**Pull request closed without merging**
