### PR TITLE
feat: set workspace name to com_github_google_copybara

### LINKED ISSUE #149: As a Bazel user, I want to change this workspace's name to be more consistent with other Bazel workspace names
> One suggestion I have is to rename this workspace to something more canonical in the Bazel ecosystem -- something along the lines of `io_copybara` or `com_google_copybara`. If the maintainers agree with this, I'll happily make the changes within this PR (in a separate commit from the addition of the macros).

_Originally posted by @sudoforge in https://github.com/google/copybara/issues/146#issuecomment-735875407_

### PR DESCRIPTION
**Pull request by sudoforge**
closes #149

### CODE REVIEW

**Comment by sudoforge** [comment]
I think this should be merged prior to #146 to avoid "changing the public interface", so to speak. E.g., it's easier for us to change the workspace name here and _then_ add documentation instructing users on how to load this workspace into theirs, rather than the other way around.

**Comment by mikelalcon** [comment]
Hi! 

Thanks for the contribution. Test don't seem to work with this change.

You can test yourself with

```
bazel test //...
```

**Comment by sudoforge** [comment]
Aha, that was tricky to track down, but the issue is that the failing tests use `TEST_SRCDIR` concatenated with `copybara/<path>` to access runfiles, e.g. from `//copybara/integration:reference_doc_test.sh`:

```
source "${TEST_SRCDIR}/copybara/third_party/bazel/bashunit/unittest.bash"
```

when instead they should be using either `$PWD` (or using relative paths), or using `TEST_WORKSPACE` instead of hard-coding the workspace name.

I opted to use `TEST_WORKSPACE`.

**Comment by sudoforge** [comment]
Is there any way we can surface the output of the `import/copybara` to external contributors? It'd be nice to see _why_ it's failing and be able to fix it without waiting for your team to have cycles.

**Comment by sudoforge** [comment]
Any idea why the `import/copybara` check doesn't appear to be running for the latest commit?

**Comment by mikelalcon** [comment]
Our Copybara migration failed because we do a core.replace on TEST_SRCDIR. I'll fix it internally and merge this change (assuming bazel now works).

**Comment by sudoforge** [comment]
Bazel now works. I'm going to do a quick test to see if the concatenation of `TEST_SRCDIR/TEST_WORKSPACE` is necessary for all tests, or if we can just use `TEST_WORKSPACE`. Will ping here in about ten minutes.

**Comment by sudoforge** [comment]
Yeah, it's necessary for most of the tests. Going to keep it as-is (no further patches for this CL).

**Comment by mikelalcon** [comment]
Sounds good. I'm running the internal tests and change our import to accept
the change.

Thanks again for the contribution and the patience :)

**Comment by sudoforge** [comment]
Sure thing! Rebased the latest master onto this tree.

After this is merged, we can get #146 merged in -- I'll rebase that tree against this to prep it.

**Comment by mikelalcon** [comment]
I wanted to give an update, I thought this was going to be 5m internally but `.resolve(System.getenv("TEST_WORKSPACE")` is giving me some trouble. Nothing terrible but I might not have it today. I'll modify/merge it once resolved.

**Comment by sudoforge** [comment]
I'm curious -- is `TEST_WORKSPACE` not passed in by Blaze?

**Comment by sudoforge** [comment]
Closed via 35700ca83ff63d873b69de6ada7bd63eb5aebdab.

**Pull request closed without merging**
