### PR TITLE
Support for private git repo URLs

### PR DESCRIPTION
**Pull request by menny**

### CODE REVIEW

**Comment by menny** [comment]
@mikelalcon this change is completely biased for our environment. I wasn't expecting this to be taken as is, tbh :)

The main issue I'm trying to fix here is, as you suspected, support for internal git.
URI re-writing is not needed - I agree - I believe I added that so the produced URL will explicitly say which protocol is used, and I can remove it if you wish.

I used two regex patterns to distinguish between file (local) URIs and remotes: remote URIs have a very specific structure, and I wanted to be thorough. 

Thoughts?

**Comment by menny** [comment]
Or.. I can completely remove this check (or just leave the `not http` validation).
Without this validation code, the responsibility for accepting and verifying falls on the VCS (git) process

**Comment by mikelalcon** [comment]
K, what about this:

$ git diff
diff --git a/java/com/google/copybara/git/GitRepository.java b/java/com/google/copybara/git/GitRepository.java
index a4f84ff4..eb5c2402 100644
--- a/java/com/google/copybara/git/GitRepository.java
+++ b/java/com/google/copybara/git/GitRepository.java
@@ -56,6 +56,7 @@ import com.google.copybara.util.FileUtil;
 import com.google.re2j.Matcher;
 import com.google.re2j.Pattern;
 import java.io.IOException;
+import java.net.URI;
 import java.nio.charset.StandardCharsets;
 import java.nio.file.FileSystems;
 import java.nio.file.Files;
@@ -91,7 +92,7 @@ public class GitRepository {

   // TODO(malcon): Make this generic (Using URIish.java)
   private static final Pattern FULL_URI = Pattern.compile(
-      "([a-z][a-z0-9+-]+@github.com.*|^[a-z][a-z0-9+-]+://.*)$");
+      "([a-z][a-z0-9+-]+@[a-zA-Z0-9_.-]+(:.+)?|^[a-z][a-z0-9+-]+://.*)$");

   private static final Pattern LS_TREE_ELEMENT = Pattern.compile(
       "([0-9]{6}) (commit|tag|tree|blob) ([a-f0-9]{40})\t(.*)");
diff --git a/javatests/com/google/copybara/git/GitRepositoryTest.java b/javatests/com/google/copybara/git/GitRepositoryTest.java
index d1b1c897..6f13e9de 100644
--- a/javatests/com/google/copybara/git/GitRepositoryTest.java
+++ b/javatests/com/google/copybara/git/GitRepositoryTest.java
@@ -533,11 +533,25 @@ public class GitRepositoryTest {
   public void validateUrl() throws Exception {
     doValidateUrl("ssh://git@github.com:foo/foo.git");
     doValidateUrl("https://github.com/foo/foo");
+    doValidateUrl("https://localhost:33333/foo/bar");
+    doValidateUrl("https://localhost:33333/foo/bar?some_arg=1&other_arg=2");
     doValidateUrl("protocol://some/url");
     doValidateUrl("git@github.com:foo/foo.git");
+    doValidateUrl("ssh://git@private.com:foo/foo.git");
+    doValidateUrl("ssh://git@private.com/foo/foo.git");
+    doValidateUrl("git@internal-git.mycompany.net:client_repo/mobile-apps.git");
+    doValidateUrl("git@internal-git.mycompany.net:9811/client_repo/mobile-apps.git");
+    doValidateUrl("git@internal-git.mycompany.net:9811:client_repo/mobile-apps.git");
+    doValidateUrl("https://internal-git.mycompany.net/client_repo/mobile-apps.git");
+    doValidateUrl("https://internal-git.mycompany.net/client_repo/mobile-apps");
+    doValidateUrl("https://internal-git.mycompany.net:8911/client_repo/mobile-apps");
+
     // A folder is a valid url. We do a sanity check internally that the directory exist. See
     // #invalidUrl test for a failure case.
-    doValidateUrl(workdir.toString());
+    doValidateUrl(workdir.toFile().getAbsolutePath());
+    doValidateUrl("file://" + workdir.toFile().getAbsolutePath());
+    doValidateUrl("file:///tmp/copybara-test/");
+    doValidateUrl("file:///tmp/localhost:3333/");
   }

---------------

I basically relaxed the regex a bit without changing it too much and added your test cases. If we want to go beyond that we should probably add jgit URlish.java instead.

**Comment by menny** [comment]
looks good to me

**Comment by menny** [comment]
Thank you

**Pull request closed without merging**
